import * as fs from 'fs'
import * as path from 'path'
import { GCodeAnalysis } from '../types'

export class GCodeAnalyzer {
  analyze(filePath: string): GCodeAnalysis {
    const content = fs.readFileSync(filePath, 'utf-8')
    const lines = content.split('\n')
    const fileName = path.basename(filePath)

    let totalLayers = 0
    let printableLines = 0
    let estimatedSeconds = 0
    let filamentUsedMm = 0
    let slicerName = 'Unknown'
    let bedTemp = 0
    let hotendTemp = 0
    let lastZ = -1
    let lastE = 0

    for (const line of lines) {
      const trimmed = line.trim()

      // Count printable lines (non-empty, non-comment)
      const cmd = trimmed.split(';')[0].trim()
      if (cmd) printableLines++

      // Layer detection from slicer comments
      if (trimmed.startsWith(';LAYER:') || trimmed.startsWith(';LAYER_CHANGE')) {
        totalLayers++
      }

      // Slicer detection
      if (trimmed.includes('generated by') || trimmed.includes('Generated with') || trimmed.includes('Slicer')) {
        if (trimmed.toLowerCase().includes('cura')) slicerName = 'Cura'
        else if (trimmed.toLowerCase().includes('prusaslicer')) slicerName = 'PrusaSlicer'
        else if (trimmed.toLowerCase().includes('orcaslicer')) slicerName = 'OrcaSlicer'
        else if (trimmed.toLowerCase().includes('creality')) slicerName = 'Creality Print'
      }

      // Estimated time from slicer
      const timeMatch = trimmed.match(/;TIME:(\d+)/)
      if (timeMatch) estimatedSeconds = parseInt(timeMatch[1], 10)

      // Filament usage from slicer
      const filamentMatch = trimmed.match(/;Filament used:\s*([\d.]+)m/)
      if (filamentMatch) filamentUsedMm = parseFloat(filamentMatch[1]) * 1000

      // Temperature extraction
      if (cmd.startsWith('M140') || cmd.startsWith('M190')) {
        const sMatch = cmd.match(/S(\d+)/)
        if (sMatch) bedTemp = parseInt(sMatch[1], 10)
      }
      if (cmd.startsWith('M104') || cmd.startsWith('M109')) {
        const sMatch = cmd.match(/S(\d+)/)
        if (sMatch) hotendTemp = parseInt(sMatch[1], 10)
      }

      // Z-based layer counting (fallback)
      if (totalLayers === 0) {
        const zMatch = cmd.match(/G[01]\s.*Z([\d.]+)/)
        if (zMatch) {
          const z = parseFloat(zMatch[1])
          if (z > lastZ) {
            lastZ = z
          }
        }
      }

      // Filament tracking from E values (fallback)
      if (filamentUsedMm === 0) {
        const eMatch = cmd.match(/E([\d.]+)/)
        if (eMatch) {
          const e = parseFloat(eMatch[1])
          if (e > lastE) {
            lastE = e
          }
        }
      }
    }

    // Fallback layer count from Z changes
    if (totalLayers === 0 && lastZ > 0) {
      totalLayers = Math.round(lastZ / 0.2) // Assume 0.2mm layer height
    }

    if (filamentUsedMm === 0) {
      filamentUsedMm = lastE
    }

    // Rough filament weight (1.75mm PLA, density ~1.24 g/cm³)
    const filamentDiameter = 1.75
    const filamentArea = Math.PI * (filamentDiameter / 2) ** 2 // mm²
    const filamentVolume = filamentUsedMm * filamentArea // mm³
    const filamentUsedG = (filamentVolume / 1000) * 1.24 // grams

    return {
      filePath,
      fileName,
      totalLines: lines.length,
      printableLines,
      totalLayers,
      estimatedSeconds,
      filamentUsedMm,
      filamentUsedG: Math.round(filamentUsedG * 10) / 10,
      slicerName,
      bedTemp,
      hotendTemp,
    }
  }
}
